### ISSUE TITLE
Fix public directory proxy

### ISSUE THREAD

**Issue by Pierstoval** [Orbitale/Rymfony#31]
For now, when you make an HTTP request to a directory like `http://127.0.0.1:8000/admin/` and the directory _actually_ exists in the server, Rymfony's `proxy_server` will try to render it, instead of passing it to FastCGI.

This kind of directory pass shouldn't happen, and instead the whole path should be forwared to the FastCGI process.

Either the `get_render_static_path()` function should be changed in `proxy_server.rs`, or the `let render_static ...` that's created just after. Feel free to check 😄

**Comment by matyo91** [comment]
For me, when `handle_fastcgi` is called `script_filename` param should be `request_path` full path instead of `script_filename`.

But then, when calling a directory forwarded to FastCGI process, I get `No input file specified.` and only php files work well.

**Comment by Pierstoval** [comment]
Do you have a proper reproducer @matyo91 so I can check it myself?

**Comment by matyo91** [comment]
To reproduce it, i made a new branch `proxy_repository` with two commits  :
- the first commit https://github.com/matyo91/Rymfony/commit/14c539bd3203efa532f05ba6f7dc85120e28ae22
Here I use force to always use FastCGI. When you request http://127.0.0.1:8000/toto, i got "Hey! It works!" because the fallback is `script_filename` at any folder case.
- the next commit https://github.com/matyo91/Rymfony/commit/20e1bf312962e92a3266585db5d7968a93387ffc
I always force FastCGI. When you request an existing directory request http://127.0.0.1:8000/toto, i got `Internal server error "502"` and http://127.0.0.1:8000/toto/ i got `No input file specified.`

When I compare result of php -S 127.0.0.1:8000 for request request `http://127.0.0.1:8000/toto` and request `http://127.0.0.1:8000/toto/` i got a nice rendered 404 message `Not found`

And more when `print_r($_SERVER);` on `http://127.0.0.1:8000/toto/toto.php`
```
[SCRIPT_NAME] => /toto/toto.php
[SCRIPT_FILENAME] => /Users/math/Sites/tests/Rymfony/toto/toto.php
```

**Comment by Pierstoval** [comment]
Thanks for the explanation, will check when I'll have more time :)

**Comment by matyo91** [comment]
Yea, i have no clue for now how to reproduce the `404 not found` from FastCGI in rust as it is done when using `php -S host:port`

**Comment by Pierstoval** [comment]
Maybe it's an issue related to the `php -S host:port` implementation that doesn't support FastCGI? I mean, `php -S ` exposes a web server, not a FastCGI process.

In such case, I'm undecided on what to do:

* If the SAPI is FCGI (with either `php-fpm` or `php-cgi`), run the FastCGI handler
* If the SAPI is not FCGI, choose between:
  * Don't support it (easier, but maybe some people might not like it)
  * Run a true HTTP proxy.

**Comment by Pierstoval** [comment]
I have fixed several issues with the latest commits:

* Swapped `SERVER_PORT` and `REMOTE_PORT` (I seem to have accidentally put them in the wrong order)
* Enhanced and fixed other FastCGI params, such as `DOCUMENT_URI`, `SCRIPT_FILENAME` and `SCRIPT_NAME`. They didn't cause any issue to me, but they were not "proper", according to the tests I've made
* I fixed the issues with the `get_render_static_path()` function, it was only checking directories, but it needed to check for files...

I'm going to close this issue, feel free to ask for reopening if the problem appears again 👍
