### ISSUE TITLE
Forks cannot build with Github actions

### ISSUE THREAD

**Issue by kevinpapst** [Orbitale/Rymfony#40]
With your updated CI setup, it is not possible to use the Github actions on forks due to the missing secrets.

I would propose to either split up `CI.yaml` into two files:
- CI.yaml - runs on all branches `*` (which then can be used by forks / pull requests as well)
- release.yaml (runs only on `main` and executes only the release steps)

Or minimum change: reorder steps, so the release steps will fail at the end.
That way contributors could still see the build output in Github action, example: https://github.com/kevinpapst/rymfony/actions/runs/379088085

I can work on a PR if you agree on one of the solutions.

**Comment by Pierstoval** [comment]
Well, having 2 files was my initial idea, but then I discovered that we could add `if` statements in steps.

I'd rather have one single build and add `if` statements in steps themselves instead, because building the project will always be the same for every platform in the end, and I'm not sure duplicating all the steps is useful, and will probably take longer

**Comment by kevinpapst** [comment]
Hm, true: adding the if `branch = main` to the ssh-key and release steps should be sufficient as well.

PR incoming ...
