### ISSUE TITLE
Do not launch PHP if no entrypoint found

### ISSUE THREAD

**Issue by jbcr** [Orbitale/Rymfony#66]
If the PHP entry point is not a file (from the argument `passthru` or default file), do not start PHP and serve all files statically.

**Comment by Pierstoval** [comment]
I don't agree with that. Entrypoint not being a file isn't a use-case to me.

If we wanted to only serve static files, I'd instead go for another RFC and recommend an entire `--static` option, and in such case, we could use that flag to completely disable PHP support, for instance.

This would be perfect for people coding with something else than PHP, and possibly open the path for a `--watch` option of some sort (in the far far future).

This issue is a 👎 to me

**Comment by jbcr** [comment]
OK
